version: '3.8'

services:
  web:
    container_name: schedule
    build:
      context: ./src
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./src/mysql/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src/
        target: /go/app
    networks:
      - golang_app_network

  db:
    container_name: db
    build:
      context: ./src/mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/amd64
    ports:
      - 3306:3306
    env_file:
      - ./src/mysql/.env
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - type: bind
        source: ./src/mysql/init
        target: /docker-entrypoint-initdb.d
    networks:
      - golang_app_network

volumes:
  mysql_data:
    name: mysql_volume

networks:
  golang_app_network:
    external: true
