db:
  driver: mysql
  database: are-you-free
  user: test_user
  password: password
  root_password: root_password
  path: test_user:password@tcp(db:3306)/are-you-free?charset=utf8&parseTime=true

auth:
  jwtSecretKey: some secret key of jwt
